version: 2.1

jobs:
  run_tests:
    - steps:
      - run: 
          name : Install dependencies 
          command: | 
            npm install
      - run:
          name: Run unit tests
          command: |
            npm test
workflows:
  build_test:
    jobs:
      - run_tests